// canvas
export const CANVAS_DIMENSION_UPDATE = 'CANVAS_DIMENSION_UPDATE';
export const CANVAS_SET_ACTIVE_COMPONENT = 'CANVAS_SET_ACTIVE_COMPONENT';
export const CANVAS_SET_FOCUS_COMPONENT = 'CANVAS_SET_FOCUS_COMPONENT';
export const CANVAS_START_DRAGGING = 'CANVAS_START_DRAGGING';
export const CANVAS_STOP_DRAGGING = 'CANVAS_STOP_DRAGGING';


// schema
export const SCHEMA_ADD_COMPONENT = 'SCHEMA_ADD_COMPONENT';
export const SCHEMA_REMOVE_COMPONENT = 'SCHEMA_REMOVE_COMPONENT';
export const SCHEMA_UPDATE_COMPONENT = 'SCHEMA_UPDATE_COMPONENT';
export const SCHEMA_UPDATE_PROPS = 'SCHEMA_UPDATE_PROPS';
export const SCHEMA_UPDATE_CHILDREN = 'SCHEMA_UPDATE_CHILDREN';

// configer