// canvas
export const CANVAS_DIMENSION_UPDATE = 'CANVAS_DIMENSION_UPDATE';

// picker
export const START_DRAG_PICKER = 'START_DRAG_PICKER';
export const FINISH_DRAG_PICKER = 'FINISH_DRAG_PICKER';
export const UPDATE_PICKER_POSITION = 'UPDATE_PICKER_POSITION';

// schema
export const SCHEMA_ADD_COMPONENT = 'SCHEMA_ADD_COMPONENT';
export const SCHEMA_REMOVE_COMPONENT = 'SCHEMA_REMOVE_COMPONENT';
export const SCHEMA_UPDATE_COMPONENT = 'SCHEMA_UPDATE_COMPONENT';
