// device
export const SET_DEVICE = 'SET_DEVICE';

// sketch
export const SKETCH_SET_ACTIVE_COMPONENT = 'SKETCH_SET_ACTIVE_COMPONENT';
export const SKETCH_SET_FOCUS_COMPONENT = 'SKETCH_SET_FOCUS_COMPONENT';
export const SKETCH_MOUSE_IN = 'SKETCH_MOUSE_IN';
export const SKETCH_MOUSE_OUT = 'SKETCH_MOUSE_OUT';


// schema
export const SCHEMA_ADD_COMPONENT = 'SCHEMA_ADD_COMPONENT';
export const SCHEMA_REMOVE_COMPONENT = 'SCHEMA_REMOVE_COMPONENT';
export const SCHEMA_UPDATE_COMPONENT = 'SCHEMA_UPDATE_COMPONENT';
export const SCHEMA_UPDATE_PROPS = 'SCHEMA_UPDATE_PROPS';
export const SCHEMA_UPDATE_CHILDREN = 'SCHEMA_UPDATE_CHILDREN';

// configer
